/*------------------------------------------------
 *------------------------------------------------
 * ||id     		:   112 0821 042
 * |name   		:   Alim Ul Karim
 * |email  		:   alim.karim.nsu@gmail.com
 * |course 		:   CSE 115.2 
 * |blog   		:   http://bit.ly/auk-blog
 * |linkedin            :   http://linkd.in/alim-ul-karim
 *------------------------------------------------
 *------------------------------------------------
 */
package org.bd.dev.restaurantmanagement.mainpackage;

import org.bd.dev.res.database.items.forms.CommonJPanel;
import org.jdesktop.application.Action;


/**
 *
 * @author Alim
 */
public class CommonForm extends javax.swing.JFrame implements ISoftwareInformation {

    public CommonJPanel CPanel = null;

    /** Creates new form CommonForm */
    public CommonForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setName("Form"); // NOI18N

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.bd.dev.restaurantmanagement.mainpackage.RestaurantManagementApp.class).getContext().getResourceMap(CommonForm.class);
        jMenu1.setText(resourceMap.getString("jMenu1.text")); // NOI18N
        jMenu1.setName("jMenu1"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(org.bd.dev.restaurantmanagement.mainpackage.RestaurantManagementApp.class).getContext().getActionMap(CommonForm.class, this);
        jMenuItem1.setAction(actionMap.get("Save")); // NOI18N
        jMenuItem1.setText(resourceMap.getString("jMenuItem1.text")); // NOI18N
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAction(actionMap.get("AddMaster")); // NOI18N
        jMenuItem2.setIcon(resourceMap.getIcon("Add.icon")); // NOI18N
        jMenuItem2.setText(resourceMap.getString("jMenuItem2.text")); // NOI18N
        jMenuItem2.setName("jMenuItem2"); // NOI18N
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAction(actionMap.get("AddDetails")); // NOI18N
        jMenuItem3.setIcon(resourceMap.getIcon("Add.icon")); // NOI18N
        jMenuItem3.setText(resourceMap.getString("jMenuItem3.text")); // NOI18N
        jMenuItem3.setToolTipText(resourceMap.getString("jMenuItem3.toolTipText")); // NOI18N
        jMenuItem3.setName("jMenuItem3"); // NOI18N
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAction(actionMap.get("DeleteMaster")); // NOI18N
        jMenuItem4.setIcon(resourceMap.getIcon("delete.icon")); // NOI18N
        jMenuItem4.setText(resourceMap.getString("jMenuItem4.text")); // NOI18N
        jMenuItem4.setToolTipText(resourceMap.getString("jMenuItem4.toolTipText")); // NOI18N
        jMenuItem4.setName("jMenuItem4"); // NOI18N
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAction(actionMap.get("DeleteDetails")); // NOI18N
        jMenuItem5.setIcon(resourceMap.getIcon("delete.icon")); // NOI18N
        jMenuItem5.setText(resourceMap.getString("jMenuItem5.text")); // NOI18N
        jMenuItem5.setName("jMenuItem5"); // NOI18N
        jMenu1.add(jMenuItem5);

        jMenuItem8.setAction(actionMap.get("SearchMaster")); // NOI18N
        jMenuItem8.setIcon(resourceMap.getIcon("search.icon")); // NOI18N
        jMenuItem8.setText(resourceMap.getString("jMenuItem8.text")); // NOI18N
        jMenuItem8.setName("jMenuItem8"); // NOI18N
        jMenu1.add(jMenuItem8);

        jMenuItem9.setAction(actionMap.get("SearchDetails")); // NOI18N
        jMenuItem9.setIcon(resourceMap.getIcon("search.icon")); // NOI18N
        jMenuItem9.setText(resourceMap.getString("jMenuItem9.text")); // NOI18N
        jMenuItem9.setName("jMenuItem9"); // NOI18N
        jMenu1.add(jMenuItem9);

        jMenuItem6.setAction(actionMap.get("Refresh")); // NOI18N
        jMenuItem6.setIcon(resourceMap.getIcon("refresh.icon")); // NOI18N
        jMenuItem6.setText(resourceMap.getString("jMenuItem6.text")); // NOI18N
        jMenuItem6.setToolTipText(resourceMap.getString("jMenuItem6.toolTipText")); // NOI18N
        jMenuItem6.setName("jMenuItem6"); // NOI18N
        jMenu1.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem7.setText(resourceMap.getString("jMenuItem7.text")); // NOI18N
        jMenuItem7.setName("jMenuItem7"); // NOI18N
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
}//GEN-LAST:event_jMenuItem1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CommonForm().setVisible(true);
            }
        });
    }

    @Action
    public void Save() {
        if (msg.showYesNo(CPanel, "Do you want to save your changes?", "Save") == true) {
            try {
                // System.out.println("ase");
                CPanel.Save();
                //System.out.println("ase2");
            } catch (Exception e) {
                ErrorMessage(e, "", "Save()");
            }
            msg.show(this, "Your data has been saved successfully.", "Saved Successfully");
        }

    }

    @Action
    public void AddMaster() {
        CPanel.AddNewToMaster();
    }

    @Action
    public void AddDetails() {
        CPanel.AddNewToDetails();
    }

    @Action
    public void DeleteMaster() {
        if (msg.showYesNo(CPanel, "Do you want to delete current Master Record(and it may also delete it's sub record(s))?", "Delete Master") == true) {
            CPanel.DeleteMaster();
        }
    }

    @Action
    public void DeleteDetails() {
        if (msg.showYesNo(CPanel, "Do you want to delete current Detail's Record?", "Delete Detail") == true) {
            CPanel.DeleteDetails();
        }
    }

    @Action
    public void Refresh() {
        if (msg.showYesNo(CPanel, "Do you want to refresh changes?", "Refresh") == true) {
            CPanel.Refresh();
            msg.show(this, "Your data has been refreshed successfully.", "Refreshed Successfully");
        }
    }

    @Action
    public void SearchMaster() {
        CPanel.SearchMasterShow();
    }

    @Action
    public void SearchDetails() {
        CPanel.SearchDetailShow();
    }
    // <editor-fold defaultstate="collapsed" desc="Error Message">

    public void ErrorMessage(Exception e, String QueryText) {
        System.out.println("{SQL Syntax: " + QueryText);
        System.err.println(e);
        System.out.println("}");
    }

    public void ErrorMessage(Exception e, String QueryText, String MethodName) {
        System.out.println("{SQL Syntax: " + QueryText + " \nMethod Name: [" + MethodName + "]");
        System.err.println(e);
        System.out.println("}");

    }

    public void ErrorMessage(String QueryText) {
        System.out.println("{SQL Syntax: " + QueryText);
        System.out.println("}");
    }

    public void ErrorMessage(Exception e) {
        System.err.println("{" + e + "}");
    }
    // </editor-fold>
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JMenuItem jMenuItem3;
    public javax.swing.JMenuItem jMenuItem4;
    public javax.swing.JMenuItem jMenuItem5;
    public javax.swing.JMenuItem jMenuItem6;
    public javax.swing.JMenuItem jMenuItem7;
    public javax.swing.JMenuItem jMenuItem8;
    public javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
